# Generated by Django 5.2 on 2025-05-04 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_savedphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
