# Generated by Django 5.2 on 2025-05-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photo_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='saved_by',
        ),
    ]
